# ---- Simulation / env ---- #
sumo:
  sumocfg: "environments/ingolstadt/sumo_files/ingolstadt21.sumocfg"
  gui: false
  ticks_per_decision: 1
  seed: 42
  time_to_teleport_s: -1

# ---- SUMO Vehicle Attributes  ---- #
vehicles:
  avg_vehicle_length_m: 5.0
  min_gap_m: 2.5

# ---- Feature config  ---- #
features:
  include_queue: true
  include_approach: true
  include_total_wait: true
  include_max_wait: true
  include_total_speed: true

# ---- Intersections (agents)  ---- #
intersections:
  defaults:
    warm_start: true
    max_detection_range_m: 50.0
    green_phase_strings: null # Default is to infer from SUMO, but can be overridden per TLS if needed
    timing_standards: # Set to zero to disable
      min_green_s: 5.0
      yellow_s: 2.0
      all_red_s: 1.0
      max_green_s: 30.0
    reward:
      function: CUMULATIVE_WAIT_DIFF        # QUEUE | TOTAL_WAIT | CUMULATIVE_WAIT_DIFF
      normalise: true

  # TLS ids and custom overrides
  list:
    - id: "tlN1"
    - id: "tlN2"
    - id: "tlN3"
    - id: "tlN4"
    - id: "tlN5"
    - id: "tlN6"
    - id: "tlN7"
    - id: "tlN8"
    - id: "tlN9"
    - id: "tlN10"
    - id: "tlN11"
    - id: "tlN12"
    - id: "tlN13"
    - id: "tlN14"
    - id: "tlN15"
    - id: "tlN16"
    - id: "tlN17"
    - id: "tlN18"
    - id: "tlN19"
    - id: "tlN20"
    - id: "tlN21"
